### ISSUE TITLE
Composer2 - Uncaught Error: Class "Phar" not found in /usr/local/bin/composer:23

### ISSUE THREAD

**Issue by williamdes** [composer/composer#10097]
Using 
```yaml
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: none, mbstring <----------------------------- missing phar
                  coverage: xdebug
            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"
```

The fix: https://github.com/phpmyadmin/sql-parser/commit/eabb78dac981503404eb4e6f8a244ae1754b2ffd

I think you could add some method to check if the class exists and not throw an error
Feel free to close this is you do not agree :)
