### ISSUE TITLE
Docker NPM Install Error: require.@selectize/selectize is invalid

### ISSUE THREAD

**Issue by dan-burt** [composer/composer#10918]
My `composer.json`:

```
{
    "require": {
        "mongodb/mongodb": "^1.8.0",
        "vlucas/phpdotenv": "^5.3.0",
        "auth0/auth0-php": "^7.9.0",
        "@selectize/selectize": "^0.13.5"
    },
    "provide" : {
    	"ext-mongodb": "*"
	}
}
```

Output of `composer diagnose`:

My apologies - I do not know how to run this, as `composer` for me is via a Docker container that runs then stops ahead of my main web app.

This is the docker-composer.yml (uses my own image, a minority tweaked PHP.ini for MongoDB use) used to deploy this environment:

```
version: '2'

services:
  webapp:
    image: redswitch/php-mongodb:8.0-1.13.0
    container_name: webapp
    volumes:
      - ./html:/var/www/html
      - ./php/mongodb.php.ini:/usr/local/etc/php/conf.d/mongodb.php.ini
    restart: always
    environment:
      - VIRTUAL_HOST=webapp.domain.com
      - LETSENCRYPT_HOST=webapp.domain.com
      - LETSENCRYPT_EMAIL=webmaster@domain.com
      - "TZ=Europe/London"
    ports:
      - 80
    expose:
      - 80
    restart: unless-stopped
    
  composer:
    image: composer:2.3
    command: ["composer", "install"]
    volumes:
      - ./html:/app

networks:
  default:
    external:
      name: nginx-proxy-net
```

When I run this command (in correct working directory): 

```
docker-compose up -d
```

I get the following output: 

The output from the `composer` container is:

> ,
> In RootPackageLoader.php line 162:,
>                                                                                ,
>   require.@selectize/selectize is invalid, it should have a vendor name, a fo  ,
>   rward slash, and a package name. The vendor and package name can be words s  ,
>   eparated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z  ,
>   0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$".                                ,
>                                                                                ,
> ,
> install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...],
> ,

And I expected this to happen:

I would expect the `composer` container to exit gracefully / no error codes and my resulting web app environment to allow use of the Selectize.js component.
