### ISSUE TITLE
composer install failed using github apps token

### ISSUE THREAD

**Issue by ishii1648** [composer/composer#11064]
I am facing issue while composer install including libraries in private Github repository. I want to authenticate using [Github Apps](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps) not personal access token on Github Action.

I want to know whether it is possible to composer install using Github Apps. Cloud you tell me about this?

#### ci.yml

```
jobs:
  composer-install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP 7.4
        run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: [app id]
          installation_id: [installation id]
          private_key: [private key]
      - name: Install PHP package
        env:
          SUPER_SECRET: ${{ steps.generate_token.outputs.token }}
        run: |
          composer config --global github-oauth.github.com ${{ env.SUPER_SECRET }}
          composer install
```

### error on Github Action

```
Error: Failed to execute git clone --mirror -- '***github.com/org-name/repository-name.git' '/home/runner/.cache/composer/vcs/https---github.com-org-name-repository-name.git/'

Cloning into bare repository '/home/runner/.cache/composer/vcs/https---github.com-org-name-repository-name.git'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/org-name/repository-name.git/'

In Git.php line 471:
                                                                               
  [RuntimeException]                                                           
  Failed to execute git clone --mirror -- '***gi  
  thub.com/org-name/repository-name.git' '/home/runner/.cache/compo  
  ser/vcs/https---github.com-org-name-repository-name.git/'          
                                                                               
  Cloning into bare repository '/home/runner/.cache/composer/vcs/https---gith  
  ub.com-org-name-repository-name.git'...                            
  remote: Support for password authentication was removed on August 13, 2021.  
  remote: Please see https://docs.github.com/en/get-started/getting-started-w  
  ith-git/about-remote-repositories#cloning-with-https-urls for information o  
  n currently recommended modes of authentication.                             
  fatal: Authentication failed for 'https://github.com/org-name/libraries.git/'         
```

**Comment by stof** [comment]
Looking at the doc of https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#http-based-git-access-by-an-installation, you need to use `x-access-token` as username when using an installation access token as password.

**Comment by stof** [comment]
And the `github-oauth` config settings sets it to `x-oauth-basic` instead

**Comment by ishii1648** [comment]
@stof 
Thank you so much. I spent a lot of time about this but solved thanks to your advice. This is finally source code of Github actions.

```
jobs:
  composer-install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP 7.4
        run: sudo update-alternatives --set php /usr/bin/php7.4
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: [app id]
          installation_id: [installation id]
          private_key: [private key]
      - name: Install PHP package
        env:
          SUPER_SECRET: ${{ steps.generate_token.outputs.token }}
        run: |
          composer config --global -a http-basic.github.com x-access-token ${{ steps.generate_token.outputs.token }}
          composer install
```
