### ISSUE TITLE
A question about caching the Composer cache dir in GitHub Actions

### ISSUE THREAD

**Issue by gggeek** [composer/composer#11191]
Just about every configuration example I have seen for speeding up the "composer install" phase in a GitHub Action workflow by storing the cache dir of Composer has, as part of the cache key, the OS in use, the version of PHP in use, and a hash of the Composer lock file.

An example, taken from [GitHub Actions](https://github.com/composer/composer/issues/9055#issuecomment-662064218) is:

```yaml
      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"
```

My question is: knowing that GHA caches are immutable (ie. once created they can not be updated) but also that Composer should be able to update the files in its cache dir _for the current run_ after the cache dir has been unpacked from the cache, and that GHA will restore the first cache it finds which matches a restore-keys value, would it not make sense to use a wider set of values for `restore-keys`?
After all, the worst that can happen, if we restore a not-really-matching composer cache dir, is that we will be priming it with packages which are not used by the current build.

The only downsides I can see are:
- if Composer does store in its cache dir package metadata, which I think it does not, this schema will break
- if the time spent unpacking a GHA cache which is filled with, say, 50% unused packages, is less than the time Composer would take by downloading all packages from source

This is the example configuration I'd use:

```yaml
      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "composer-${{ matrix.os }}-${{ matrix.php-version }}-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: |
              composer-${{ matrix.os }}-${{ matrix.php-version }}-${{ matrix.dependencies }}-
              composer-${{ matrix.os }}-${{ matrix.php-version }}-
              composer-${{ matrix.os }}-
              composer-
```
