### ISSUE TITLE
Apparent inconsistency in package `pretty_version` between require and update commands

### ISSUE THREAD

**Issue by ChaseOnTheWeb** [composer/composer#11433]
My `composer.json`:

```json
{
    "require-dev": {
        "joachim-n/composer-manifest": "^1.1",
        "grasmash/drupal-security-warning": "1.x-dev"
    },
    "config": {
        "allow-plugins": {
            "joachim-n/composer-manifest": true,
            "grasmash/drupal-security-warning": true
        }
    }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK git version 2.38.4
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.5
PHP version: 8.2.5
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 3.0.8 7 Feb 2023
cURL version: 8.0.1 libz 1.2.13 ssl OpenSSL/3.0.8
zip: extension present, unzip present, 7-Zip present (7z)
```

When I run this command: 

```
composer require --dev joachim-n/composer-manifest
composer require --dev grasmash/drupal-security-warning:1.x-dev
```

I get the following output in `composer-manifest.yaml` (created by `joachim-n/composer-manifest` plugin): 

```yaml
packages:
    grasmash/drupal-security-warning: '1.x-dev:848fd28335c984ca1ceb9454f7d636465db5c5f8'
    joachim-n/composer-manifest: 1.1.5
    symfony/polyfill-ctype: v1.27.0
    symfony/yaml: v6.2.7
```

Then, I run `composer update -W` and get the output in `composer-manifest.yaml` (the first package's `pretty_version` has changed):
```yaml
packages:
    grasmash/drupal-security-warning: 'dev-master:848fd28335c984ca1ceb9454f7d636465db5c5f8'
    joachim-n/composer-manifest: 1.1.5
    symfony/polyfill-ctype: v1.27.0
    symfony/yaml: v6.2.7
```

Then, I run `rm -rf vendor && composer install` and am back to:
```yaml
packages:
    grasmash/drupal-security-warning: '1.x-dev:848fd28335c984ca1ceb9454f7d636465db5c5f8'
    joachim-n/composer-manifest: 1.1.5
    symfony/polyfill-ctype: v1.27.0
    symfony/yaml: v6.2.7
```

---

There seems to be an inconsistency in the package object's `pretty_version` when running `composer update` vs. `composer require` or `composer install`.

The [Composer Manifest plugin](https://github.com/joachim-n/composer-manifest/blob/master/Plugin.php#L63) is simply calling Composer\Package\Package::getFullPrettyVersion(), and thus is only relevant as an example of how this behavior is causing a problem.

I have other examples of this happening when requiring an @dev package; `drupal/font_awesome:1.x-dev@dev` flips between `1.x-dev` and `dev-1.x` in the above steps (I wanted to keep the above steps to simple packages with minimal dependencies).
