### ISSUE TITLE
Composer Cannot install / update with respository private

### ISSUE THREAD

**Issue by peersbio** [composer/composer#1942]
Loading composer repositories with package information
Updating dependencies (including require-dev)
  -- Installing cartalyst/dependencies (dev-master bc077b1)
     Authentication required (nodeload.github.com)
        username: 
        password:

After I enter username and password, I got the messaage donwloading 100% and ask me to login again and again.  (please see the below)

```
Downloading:  100%
 Authentication required (nodeload.github.com)
    username: 
    password:
```
