### ISSUE TITLE
Authentication required, while manual file download succeeds

### ISSUE THREAD

**Issue by TheDevilOnLine** [composer/composer#2439]
Since today Composer starts asking for Github API authentication, but if you access the url's it gives 403 errors on by hand, the files are downloaded perfectly fine!

```
  - Removing doctrine/orm (2.3.4)
  - Installing doctrine/orm (v2.4.1)
    Authentication required (api.github.com):
      Username:
      Password:
    Downloading: 100%
    Authentication required (api.github.com):
      Username:
      Password:
    Downloading: 100%
    Authentication required (api.github.com):
      Username:
      Password:
    Downloading: 100%
    Downloading: connection...


  [Composer\Downloader\TransportException]
  The 'https://api.github.com/repos/doctrine/doctrine2/zipball/84373d05a4198ec380918d535abf83c454c3867f' URL could not be accessed: HTTP/1.1 403 Forbidden
```
