### ISSUE TITLE
Why repositories property is root-only ?

### ISSUE THREAD

**Issue by maidmaid** [composer/composer#4754]
Hello,

In my private repositories, I have ``vendor/root`` package that requires ``vendor/a`` package that requires ``vendor/b`` package. So, I did :

- in composer.json of ``vendor/root`` package :
```yml
{
    "name": "vendor/root",
    "require": { "root/a": "*" },
    "repositories": { { "type": "vcs", "url": "git@vendor.com:vendor/a.git" } }
}
```

- and in composer.json of ``vendor/a`` package :
```yml
{
    "name": "vendor/a",
    "require": { "root/b": "*" },
    "repositories": { { "type": "vcs", "url": "git@vendor.com:vendor/b.git" } }
}
```

But according [doc](https://getcomposer.org/doc/04-schema.md#repositories), ``repositories`` property is root-only.
> Repositories are not resolved recursively. You can only add them to your main composer.json. Repository declarations of dependencies' composer.jsons are ignored.

And resolving package doesn't work because ``vendor/b`` is not found.

But if I move ``vendor/b`` repository in ``vendor/root`` as doc wants, it works, like that : 
```yml
{
    "name": "vendor/root",
    "require": { "root/a": "*" },
    "repositories": { 
        { "type": "vcs", "url": "git@vendor.com:vendor/a.git" }
        { "type": "vcs", "url": "git@vendor.com:vendor/b.git" }
    }
}
```

But I think the way I did it makes more sense. Actually, if ``vendor/b`` is a require of 100 distinct projects and I want add ``vendor/c`` private package as require of `vendor/b`, I must add ``repositories`` property of ``vendor/c`` in all my 100 projects. By my way I only need to add ``repositories`` property of ``vendor/c`` in ``vendor/b``.

I don't understand why ``repositories`` property is root-only. Could you explain me?
