### ISSUE TITLE
"The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

### ISSUE THREAD

**Issue by richbradshaw** [composer/composer#4789]
This worked an hour or so back, but newest version seems to be broken - it's always saying this on a system where the user has no default HOME set, just COMPOSER_HOME.

I notice that commits in version `96ff17c520b398d2a102d082bf0d4df3bd5c18a8` which I'm using reference this error message - a regression?

**Comment by jschnare** [comment]
This is affecting us too, we're explicitly setting COMPOSER_HOME and we're getting the same error.

**Comment by fosberyi** [comment]
+1 This is crashing all deploys across our system right now.

**Comment by richbradshaw** [comment]
As a heads up, you can simply run `composer self-update 1.0.0-alpha11` to fix the version of composer to a specific tagged release - that version works fine, and to be honest, running the newest version probably isn't the best idea anyway.

I wonder if `composer self-update` should just use tagged releases, and have something like `composer self-update --bleeding-edge` work as the current version does.

**Comment by fosberyi** [comment]
@richbradshaw thanks for the heads up. I still can't get this to work on ElasticBeanstalk though. Still getting that same error:

"The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

**Comment by PatrickRyan-** [comment]
Removing the composer update in your eb config should get you back up until this is resolved.

**Comment by cs278** [comment]
Can confirm. @Seldaek this totally breaks Composer.

```
$ env --ignore-environment COMPOSER_HOME=$(pwd) sh -c '( env; /home/chris/src/composer/bin/composer diagnose )'
COMPOSER_HOME=/tmp/chris/tmp.XBaZJ6vFzW
PWD=/tmp/chris/tmp.XBaZJ6vFzW

                                                                                            
  [RuntimeException]                                                                        
  The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  
                                                                                            

diagnose
```

**Comment by fosberyi** [comment]
@PatrickRyan (and everyone else who's curious), I tried removing the composer update in the eb config, and it still didn't work. I was able to finally get it to work by changing this extension script:
```
commands:
  01_update_composer:
    command: export COMPOSER_HOME=/root && /usr/bin/composer.phar self-update 1.0.0-alpha11

option_settings:
  - namespace: aws:elasticbeanstalk:application:environment
    option_name: COMPOSER_HOME
    value: /root
```
To this:

```
commands:
  01_update_composer:
    command: export HOME=/root && export COMPOSER_HOME=/root && /usr/bin/composer.phar self-update 1.0.0-alpha11

option_settings:
  - namespace: aws:elasticbeanstalk:application:environment
    option_name: COMPOSER_HOME
    value: /root
  - namespace: aws:elasticbeanstalk:application:environment
    option_name: HOME
    value: /root

```

However, this causes ssh / bash_profile issues now because of the "HOME" envvar, so It'd be great if this could get sorted so we can go back to using just COMPOSER_HOME. Nevertheless, things seem to be running again.

Thanks for your help everyone!
