### ISSUE TITLE
Composer is reformatting parameters.yml, adjusting spacing, and removing quotation marks

### ISSUE THREAD

**Issue by arderyp** [composer/composer#6256]
My `composer.json`:

```json
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "repositories": [
        {
        }
    ],
    "require": {
        "php": "^7.0",
        "symfony/symfony": "2.8.*",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "sensio/generator-bundle": "~2.3",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "twig/extensions": "1.0.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "lrotherfield/form": "~2.0",
        "guzzlehttp/guzzle": "~6.0",
        "guzzlehttp/oauth-subscriber": "0.3.*"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update
```

The following block in my parameters.yml file:

```
  one:
    id: '0fakevalue'
    key: 'fakevalue'
  two:
    id: 'fakevalue'
    key: 'fakevalue'
  three:
    id: 'fakevalue'
    key: 'fakevalue'
  four:
    id: 'fakevalue'
    key: 'fakevalue'
  five:
    id: 'fakevalue'
    key: 'fakevalue'
```

Is replaced with:

```
    one:
        id: '0fakevalue'
        key: fakevalue
    two:
        id: fakevalue
        key: fakevalue
    three:
        id: fakevalue
        key: fakevalue
    four:
        id: fakevalue
        key: fakevalue
    five:
        id: fakevalue
        key: fakevalue
```

The spacing is changed from 2 to 4 spaces.  I am guessing this is a standardization thing that is probably done intentionally.  The quotation removal, on the other hand, seems like it might be a bug... or at least very curious behavior.  The only value that doesn't have the quotation removed is the one with a leading 0.  Composer is doing something right, since that's actually the only data element where removing the quotes would break our application.  However, for standardization purposes, we'd like to keep all of these values quoted so developers are in the habit of quoting values they may add (lead by example) so as to prevent any future bugs that may arise from them entering a value with a leading zero and no quotes.  But, if composer automatically removes the quotes, this breaks our standardization/best-practice-examples and may exhibit bug potential.  I don't see any value added in removing the quotes, so was wondering if someone could shed light on this for me.
