### ISSUE TITLE
Inconsistent terminal output running scripts

### ISSUE THREAD

**Issue by MrHash** [composer/composer#6372]
My `composer.json`:

```json
{
    "scripts": {
        "rundocker": "docker run --rm php:5.6-cli php --ini",
	"rundockercompose": "docker-compose run --rm php_cli php --ini"
    }
}
```
and this docker-compose.yml
```yaml
version: "3.1"
services:
  php_cli:
    image: php:5.6-cli
```

When I run this command:

```
composer rundockercomposer
```

i get inconsistent output to the terminal, sometimes nothing, sometimes the correct output. 

Conversely:

```shell
composer rundocker
#or
docker-compose run --rm php_cli php --ini
```
always shows the expected output.
