### ISSUE TITLE
All branches are wastefully scanned when installing forked package as vcs

### ISSUE THREAD

**Issue by mpyw** [composer/composer#6396]
My `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/deeky666/dbal.git"
        }
    ],
    "require-dev": {
        "doctrine/dbal": "dev-fix-mysql57-platform"
    }
}
```

Output of `composer diagnose`:

```yaml
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```bash
composer install
```

I get the following output:

```
Loading composer repositories with package information
Reading composer.json of doctrine/dbal (2.0.0-BETA1)
Reading composer.json of doctrine/dbal (DBAL-22)
Reading composer.json of doctrine/dbal (DBAL-44)
...
...
...
(Wastefully long long fetches)
```

What's wrong?
