### ISSUE TITLE
Error when trying to install symfony/symfony with dev dependencies

### ISSUE THREAD

**Issue by schmittjoh** [composer/composer#748]
Problem occurs with the currently latest composer version.

```
sh-4.1$ composer create-project symfony/symfony --dev
Installing symfony/symfony (dev-master 49e213ce7c6b9957433c2a64a0144c9ee4b61266)
  - Installing symfony/symfony (dev-master)
    Cloning 49e213ce7c6b9957433c2a64a0144c9ee4b61266

Created project in /tmp/symfony
Installing dependencies
  - Installing twig/twig (dev-master)
    Cloning 82e73f6bf26b2301c8d7b51807660bf9ccd43020

  - Installing doctrine/common (dev-master)
    Cloning 4ac23ae8737fe7b95a7dd0f1346dbd48c7a503b0

Installing dev dependencies
Your requirements could not be solved to an installable set of packages.

        Problems:
                - Problem caused by:
                        - Installation of package "doctrine/orm" with constraint [>= 2.2.0.0, < 2.4.0.0-dev] was requested. Satisfiable by packages [doctrine/orm-2.2.2.0, doctrine/orm-2.2.1.0, doctrine/orm-2.2.0.0, doctrine/orm-2.2.9999999.9999999-dev, doctrine/orm-2.3.9999999.9999999-dev (alias of 9999999-dev)].
                        - Package "doctrine/orm-2.2.2.0" contains the rule doctrine/orm requires doctrine/common ([>= 2.2.0.0, < 2.2.99.0]). Any of these packages satisfy the dependency: doctrine/common-2.2.2.0, doctrine/common-2.2.1.0, doctrine/common-2.2.0.0.
                        - Package "doctrine/orm-2.2.1.0" contains the rule doctrine/orm requires doctrine/common ([>= 2.2.0.0, < 2.2.99.0]). Any of these packages satisfy the dependency: doctrine/common-2.2.2.0, doctrine/common-2.2.1.0, doctrine/common-2.2.0.0.
                        - Package "doctrine/orm-2.2.0.0" contains the rule doctrine/orm requires doctrine/common ([>= 2.2.0.0, < 2.2.99.0]). Any of these packages satisfy the dependency: doctrine/common-2.2.2.0, doctrine/common-2.2.1.0, doctrine/common-2.2.0.0.
                        - Package "doctrine/orm-2.2.9999999.9999999-dev" contains the rule doctrine/orm requires doctrine/common ([> 2.1.9999999.9999999, < 2.2.9999999.9999999]). Any of these packages satisfy the dependency: doctrine/common-2.2.2.0, doctrine/common-2.2.1.0, doctrine/common-2.2.0.0, doctrine/common-2.2.0.0-RC4, doctrine/common-2.2.0.0-RC5, doctrine/common-2.2.0.0-RC1, doctrine/common-2.2.0.0-RC3, doctrine/common-2.2.0.0-beta1, doctrine/common-2.2.0.0-beta2, doctrine/common-2.2.9999999.9999999-dev.
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.2.0
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.1.0
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.0.0
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.0.0-RC4
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.0.0-RC5
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.0.0-RC1
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.0.0-RC3
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.0.0-beta1
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.0.0-beta2
                        - -doctrine/common-9999999-dev|-doctrine/common-2.2.9999999.9999999-dev
                        - Installation of package "doctrine/common" with constraint == 9999999-dev was requested. Satisfiable by packages [doctrine/common-9999999-dev, doctrine/common-9999999-dev].
                        - learned: -doctrine/common-9999999-dev
                        - Installation of package "symfony/symfony" with constraint == 1.0.0.0 was requested. Satisfiable by packages [symfony/symfony-1.0.0.0].
                        - Package "doctrine/orm-2.3.9999999.9999999-dev (alias of 9999999-dev)" contains the rule doctrine/orm requires symfony/console ([> 1.9999999.9999999.9999999, < 2.9999999.9999999.9999999]). Any of these packages satisfy the dependency: symfony/symfony-2.0.9999999.9999999-dev, symfony/symfony-2.1.9999999.9999999-dev (alias of 9999999-dev), symfony/console-2.0.13.0, symfony/symfony-2.0.13.0, symfony/console-2.0.12.0, symfony/symfony-2.0.12.0, symfony/symfony-2.0.10.0, symfony/symfony-2.0.11.0, symfony/console-2.0.10.0, symfony/console-2.0.9.0, symfony/symfony-2.0.9.0, symfony/console-2.0.4.0, symfony/console-2.0.5.0, symfony/console-2.0.6.0, symfony/console-2.0.7.0, symfony/symfony-2.0.7.0, symfony/console-2.0.14.0, symfony/symfony-2.0.14.0, symfony/symfony-2.0.15.0, symfony/console-2.0.9999999.9999999-dev, symfony/console-2.1.9999999.9999999-dev (alias of 9999999-dev).
                        - -symfony/symfony-2.0.9999999.9999999-dev|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.1.9999999.9999999-dev (alias of 9999999-dev)|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.0.13.0|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.0.12.0|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.0.10.0|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.0.11.0|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.0.9.0|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.0.7.0|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.0.14.0|-symfony/symfony-1.0.0.0
                        - -symfony/symfony-2.0.15.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.13.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.12.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.10.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.9.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.4.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.5.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.6.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.7.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.14.0|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.0.9999999.9999999-dev|-symfony/symfony-1.0.0.0
                        - -symfony/console-2.1.9999999.9999999-dev (alias of 9999999-dev)|-symfony/symfony-1.0.0.0
```
