### ISSUE TITLE
outdated --strict --direct --ignore-compatible

### ISSUE THREAD

**Issue by mabar** [composer/composer#7768]
Is it possible to run `composer outdated` and fail only if new incompatible versions of dependencies were released? (something like `--ignore-compatible`)

Example:
My library depends on `nette/di:~2.4.11`. So anyone is able install `nette/di` up to `2.4.999` along with my library. So I don't care about new bugfixes because they are compatible, but I still want to know if `2.5` or `3.0` were released because it requires update in my code.

Currently I have following code in my travis build and I get notifications about every single new version of dependencies, which is really annoying.
```
    - stage: Outdated Dependencies
      if: branch = master AND type = cron
      php: 7.1
      script:
        - composer outdated --direct --strict
```

Maybe it could also work without a switch? When I run `composer install` for library which does not have `composer.lock` then latest compatible dependencies are installed. So it would be nice if it works with `composer.lock` instead of `composer.json` dependencies.
