### ISSUE TITLE
Composer in project with branch alias sometimes refuses to install dependencies

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#8579]
My `composer.json`: https://github.com/phpstan/phpstan-src/blob/master/composer.json

When I run this command:

```
composer update
```

I get the following output:

```
    - phpstan/phpstan-strict-rules 0.12.0 requires phpstan/phpstan ^0.12 -> satisfiable by phpstan/phpstan[0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.x-dev].
    - phpstan/phpstan-strict-rules 0.12.1 requires phpstan/phpstan ^0.12 -> satisfiable by phpstan/phpstan[0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.x-dev].
    - phpstan/phpstan-strict-rules 0.12.2 requires phpstan/phpstan ^0.12.6 -> satisfiable by phpstan/phpstan[0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.x-dev].
    - phpstan/phpstan-strict-rules 0.12.x-dev requires phpstan/phpstan ^0.12.6 -> satisfiable by phpstan/phpstan[0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.x-dev].
    - don't install phpstan/phpstan 0.12.0|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.1|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.2|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.3|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.4|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.5|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.6|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.7|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.8|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.9|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - don't install phpstan/phpstan 0.12.x-dev|remove phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf
    - Installation request for phpstan/phpstan-src dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf -> satisfiable by phpstan/phpstan-src[dev-ad2293bf2871cfa2b005e9acbb5889322244cfbf].
    - Installation request for phpstan/phpstan-strict-rules ^0.12 -> satisfiable by phpstan/phpstan-strict-rules[0.12.0, 0.12.1, 0.12.2, 0.12.x-dev].
```

But only sometimes. It works when I'm checked out on master. It always works in Travis CI, no matter if it's on master or a pull request or a tag. But it fails in Travis CI when I push some other branch than master, and it always fails in GitHub actions. See:

* https://github.com/phpstan/phpstan-src/pull/128/checks?check_run_id=426902574 (fails)
* https://travis-ci.org/phpstan/phpstan-src/jobs/646269381 (passes)

I'm not sure what's different in these cases and I'd expect it to work in GitHub Actions and also on other branches than master.

**Comment by ondrejmirtes** [comment]
In GitHub actions it doesn't even help to override the default behaviour and always checkout the SHA (which I expected to fix this): https://github.com/phpstan/phpstan-src/pull/128/commits/fee27da701c9782023aa36cc84a3ca5f7c76c378

**Comment by ondrejmirtes** [comment]
I also tried removing `replace` section, also doesn't help: https://github.com/phpstan/phpstan-src/pull/128/commits/ec62f690a547e0c4efb887a78ccad11b7135eac5

**Comment by localheinz** [comment]
We are observing the same in `sebastian/type`.

### `composer.json`

```json
{
    "name": "sebastian/type",
    "description": "Collection of value objects that represent the types of the PHP type system",
    "type": "library",
    "homepage": "https://github.com/sebastianbergmann/type",
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Sebastian Bergmann",
            "email": "sebastian@phpunit.de",
            "role": "lead"
        }
    ],
    "support": {
        "issues": "https://github.com/sebastianbergmann/type/issues"
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "require": {
        "php": "^7.3"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.0"
    },
    "config": {
        "platform": {
            "php": "7.3.0"
        },
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "autoload": {
        "classmap": [
            "src/"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/_fixture"
        ],
        "files": [
            "tests/_fixture/callback_function.php"
        ]
    },
    "extra": {
        "branch-alias": {
            "dev-master": "2.0-dev"
        }
    }
}
```

### `composer`

Running

```
$ tools/composer --version
```

yields

```
Composer version 1.9.2 2020-01-14 16:30:31
```
### Local Installation

Running

```
$ /tools/composer update --no-ansi --no-interaction --no-progress --no-suggest
```

locally works fine.

### Installation on GitHub Actions

Running

```
$ /tools/composer update --no-ansi --no-interaction --no-progress --no-suggest
```

on GitHub Action yields

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sebastian/type dev-f7848e788a45d1ad99fd0d9d14651e414019b9e4 -> satisfiable by sebastian/type[dev-f7848e788a45d1ad99fd0d9d14651e414019b9e4].
    - phpunit/phpunit 9.0.x-dev requires sebastian/type ^2.0 -> satisfiable by sebastian/type[2.0.x-dev].
    - Can only install one of: sebastian/type[2.0.x-dev, dev-f7848e788a45d1ad99fd0d9d14651e414019b9e4].
    - Installation request for phpunit/phpunit ^9.0 -> satisfiable by phpunit/phpunit[9.0.x-dev].
```

For reference, see , see https://github.com/sebastianbergmann/type/pull/9/checks?check_run_id=421626004.

Something that bugs me is the following: I have helped both in `sebastian/type` and `phpstan/phpstan-src` to set up the workflows (so perhaps that is the problem), but on the other hand have only experienced these issues so far when a branch-alias has been configured in `composer.json`.

**Comment by ondrejmirtes** [comment]
It's also happening in Travis when I push a non-master branch into phpstan/phpstan-src. I can't spot what's the cause though...

**Comment by xabbuh** [comment]
@ondrejmirtes In your first example, does it work if you run `COMPOSER_ROOT_VERSION=0.12.x-dev composer update` instead of only `composer update`?

**Comment by ondrejmirtes** [comment]
Yes, this works! Although I'm not sure why is it necessary in my case.

**Comment by alcohol** [comment]
Github actions use a very shallow checkout. I'm not sure if the version guesser can deal with that properly.

**Comment by Seldaek** [comment]
Yes that's why we added the COMPOSER_ROOT_VERSION env var, to fix branch builds on travis & co. No way around it really if you have circular dependencies.

**Comment by ondrejmirtes** [comment]
Thank you :)

**Comment by localheinz** [comment]
In case you come here and find this issue, there are a few options:

### Current workflow

```yml
# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  REQUIRED_PHP_EXTENSIONS: "mbstring"

jobs:
  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"

        dependencies:
          - "lowest"
          - "locked"
          - "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@1.8.1"
        with:
          coverage: "none"
          extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1.0.3"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install lowest dependencies with composer"
        if: "matrix.dependencies == 'lowest'"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"

      - name: "Install locked dependencies with composer"
        if: "matrix.dependencies == 'locked'"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies with composer"
        if: "matrix.dependencies == 'highest'"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Run auto-review tests with phpunit/phpunit"
        run: "vendor/bin/phpunit --configuration=test/AutoReview/phpunit.xml"

      - name: "Run unit tests with phpunit/phpunit"
        run: "vendor/bin/phpunit --configuration=test/Unit/phpunit.xml"

      - name: "Run integration tests with phpunit/phpunit"
        run: "vendor/bin/phpunit --configuration=test/Integration/phpunit.xml"
```

### Manually set environment variable

```diff
diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
index dc88b45..d001be7 100644
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -9,6 +9,7 @@ on:
       - "master"

 env:
+  COMPOSER_ROOT_VERSION: "1.0-dev"
   REQUIRED_PHP_EXTENSIONS: "mbstring"

 jobs:
```

### Determine from `composer.json`

```diff
diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
index dc88b45..194d3a7 100644
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -47,6 +47,9 @@ jobs:
           key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}"
           restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

+      - name: "Set COMPOSER_ROOT_VERSION environment variable"
+        run: "echo \"::set-env name=COMPOSER_ROOT_VERSION::$(jq --raw-output '.extra.\"branch-alias\".\"dev-master\"' composer.json)\""
+
       - name: "Install lowest dependencies with composer"
         if: "matrix.dependencies == 'lowest'"
         run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"
```

### Use `ergebnis/composer-root-version-action`

```diff
diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
index dc88b45..0b12e21 100644
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -47,6 +47,9 @@ jobs:
           key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}"
           restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

+      - name: "Set COMPOSER_ROOT_VERSION environment variable"
+        uses: "ergebnis/composer-root-version-action@0.1.3"
+
       - name: "Install lowest dependencies with composer"
         if: "matrix.dependencies == 'lowest'"
         run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"
```

### Use pre-built Docker image

```diff
diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
index dc88b45..ef1292f 100644
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -47,6 +47,9 @@ jobs:
           key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}"
           restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

+      - name: "Set COMPOSER_ROOT_VERSION environment variable"
+        uses: "docker://ergebnis/composer-root-version-action:0.1.3"
+
       - name: "Install lowest dependencies with composer"
         if: "matrix.dependencies == 'lowest'"
         run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest"
```

💁‍♂ For reference, see https://github.com/ergebnis/composer-root-version-action.
