### ISSUE TITLE
GitHub Actions: Permission denied for composer self-update

### ISSUE THREAD

**Issue by hugovk** [composer/composer#8678]
My `composer.json`:

```json
n/a
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.9.3 => 1.10.0)
Composer version: 1.9.3
PHP version: 7.4.3
PHP binary path: /usr/bin/php7.4
```

When I run this command:

```
composer self-update
```

I get the following output (on GitHub Actions):

```
Updating to version 1.10.0 (stable channel).
   Downloading (connecting...)Downloading (100%)         

                                                                                                
  [ErrorException]                                                                              
  rename(/home/runner/.composer/cache/composer-temp.phar,/usr/bin/composer): Permission denied  
                                                                                                

self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--set-channel-only] [--] [<version>]

##[error]Process completed with exit code 1.
```
https://github.com/hugovk/test/runs/498138460?check_suite_focus=true

And I expected this to happen (it works for me on my macOS):

```
Updating to version 1.10.0 (stable channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.9.3
```

Here's the minimal workflow file:

```yaml
name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - name: Composer update
        run: |
          composer self-update
```
