### ISSUE TITLE
Repository no-api flag also causes git hang like before

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9020]
My `composer.json`:

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:GrahamCampbell/promises.git",
            "no-api": true
        }
    ],
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (2.0.0-alpha2 => 1.10.8)
Composer version: 2.0.0-alpha2
PHP version: 7.4.7
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
composer update --no-interaction
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
```

**Comment by GrahamCampbell** [comment]
I think we want to auto-yes to such questions, right?

**Comment by alcohol** [comment]
I think `--no-interaction` implies that we at least want to make a decision there for the user. Whether that should default to yes or no, I do not know. But we should definitely not ask for input.

**Comment by Seldaek** [comment]
The only way to do this that I have found is https://github.com/composer/composer/commit/74d89d7110754aaea9b61c5a17d24b0ab2d113a8#diff-8b93719582669d35594f58bb11eed1d2L121-L130 - which requires fairly ugly hackery, and well, it doesn't seem to be a very broad problem in practice so I am not sure what we should do here. You're the first person to run into this AFAICT.. the one on the version guessing was nasty because that happened for every command but it's gone now.. This use case for git repos well yes it requires a working git connection I think it's not unreasonable to push this requirement to the user. It sucks that it blocks tho, not sure why or if we could have a cleaner hack to say we're not running interactive and it should just not prompt.

Ideally you should add the key to your servers as per https://serverfault.com/a/971922 if you can't run it interactively.

**Comment by GrahamCampbell** [comment]
That is not really possible (by which I mean, badDX), say if you are using the composer docker image in a CI workflow. The image comes up with fresh disk state, then throws away after done. I feel composer needs to implement something here to make this slicker.

I am certainly not the only one running composer like this, but I suppose almost nobody uses the no-api feature for repos, which is why this hasn't been reported.

**Comment by Seldaek** [comment]
Yes, the problem is, there is no way to do this securely without knowing the keys in advance. So if we implement anything, it'll be failing hard instead of blocking on the prompt.. That will still require you to make sure the key is in known_hosts beforehand though.

If you use the docker container, you should IMO make sure the known_hosts file is mounted into it. Maybe @alcohol can help with this.

**Comment by alcohol** [comment]
I would suggest running `ssh-keyscan github.com` in any workflow that starts from a 'clean slate'. Redirect stdout (not stderr) to either `~/.ssh/known_hosts` or `/etc/ssh/ssh_known_hosts`.

**Comment by GrahamCampbell** [comment]
> I would suggest running ssh-keyscan github.com in any workflow that starts from a 'clean slate'. Redirect stdout (not stderr) to either ~/.ssh/known_hosts or /etc/ssh/ssh_known_hosts.

The thing is, after that is run, and then composer is run, the container is destroyed, and re-created. See, for example: https://github.com/GrahamCampbell/Laravel-GitHub/blob/master/.github/workflows/tests.yml.

**Comment by Seldaek** [comment]
Then you gotta run it on every CI run.. there's really no way around this
IMO

**Comment by alcohol** [comment]
> > I would suggest running ssh-keyscan github.com in any workflow that starts from a 'clean slate'. Redirect stdout (not stderr) to either ~/.ssh/known_hosts or /etc/ssh/ssh_known_hosts.
> 
> The thing is, after that is run, and then composer is run, the container is destroyed, and re-created. See, for example: https://github.com/GrahamCampbell/Laravel-GitHub/blob/master/.github/workflows/tests.yml.

Yeah... that is the whole up- and downside of ephemeral/immutability. Your CI pipeline will have to repeat some tedious small steps over and over (though there are many ways you could implement caching here).

**Comment by alcohol** [comment]
Not the prettiest, but for example:

```
 steps:
    - uses: actions/checkout@v2
    - name: Populate ssh_known_hosts
      run: ssh-keyscan github.com > ssh_known_hosts
    - name: Pull Docker Image
      run: docker pull registry.gitlab.com/grahamcampbell/php:${{ matrix.php }}
    - name: Select Laravel
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data -v ${{ github.workspace }}/ssh_known_hosts:/etc/ssh/ssh_known_hosts --entrypoint composer registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} require "laravel/framework:${{ matrix.laravel }}.*" --no-update -n
    - name: Select HTTPlug
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data -v ${{ github.workspace }}/ssh_known_hosts:/etc/ssh/ssh_known_hosts  --entrypoint composer registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} require "php-http/httplug:^${{ matrix.httplug }}" --no-update -n
    - name: Run Composer
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data -v ${{ github.workspace }}/ssh_known_hosts:/etc/ssh/ssh_known_hosts  --entrypoint composer registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} install --prefer-dist -n -o
    - name: Run PHPUnit
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} --coverage-clover build/logs/clover.xml
    - name: Upload Coverage
      run: docker run --rm -w /data -v ${{ github.workspace }}:/data --entrypoint ocular registry.gitlab.com/grahamcampbell/php:${{ matrix.php }} code-coverage:upload --format=php-clover build/logs/clover.xml
```
