### ISSUE TITLE
caching php dependencies in a github action

### ISSUE THREAD

**Issue by staabm** [composer/composer#9055]
not sure the underlying problem is related to GitHub Actions or composer itself.

when using dependency caching like described in https://github.com/actions/cache/blob/main/examples.md#php---composer:

```
- name: Get Composer Cache Directory
  id: composer-cache
  run: |
    echo "::set-output name=dir::$(composer config cache-files-dir)"
- uses: actions/cache@v2
  with:
    path: ${{ steps.composer-cache.outputs.dir }}
    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    restore-keys: |
      ${{ runner.os }}-composer-
```

we get a ugly error condition in case the composer.json is not valid.
this happend today in our case because of a merge conflict, which was not resolved properly.

we get into a situation as follows:

![grafik](https://user-images.githubusercontent.com/120441/87669841-f3de8d00-c76e-11ea-8489-8be5bbe6049b.png)

so because of a invalid composer.json the variable which is later on used for the actions/cache@v2 `path` parameter is not properly filled and it runs into an error.

I expected the 'Get Composer Cache Directory' step should fail immediately - not the follow up step which makes it harder to reason about the cause of the error.
is there anything which could be improved here?

**Comment by Seldaek** [comment]
The problem I suppose is that `$(...)` in bash will silently swallow the error exit code of the composer process, and end up echoing an empty string.

Maybe doing `set +e` before to make bash exit on error would help, but I am not sure this applies in this case. Technically I guess the echo will still exit with a 0 code so it'll look fine.

I doubt this can be improved much..

**Comment by GrahamCampbell** [comment]
I find that it's usually faster to **not use caching** with composer 2. Composer 2 can download stuff faster in parallel than a big sequential download from the cache.

**Comment by localheinz** [comment]
@staabm 

The easiest way to avoid this kind of issue is by running

```
$ composer validate

```

before running commands relying on `composer.json` to be present.

For example, see https://github.com/ergebnis/php-library-template/blob/924d58a94ef9ca451985b0b6eae3ab2f09be96af/.github/workflows/integrate.yaml#L48-L60:

```yaml
      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.0.0"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"
```
